### ISSUE TITLE
 Panic when git tag is not available yet

### ISSUE THREAD

**Issue by hary-tiket** [typical-go/typical-rest-server#5]
```+ ./typicalw release -github-token=0661d9646e54e897e86baf27439cc0d55da9f545
time="2019-08-06T17:43:33+07:00" level=info msg="Generate new project environment at '.env'"
time="2019-08-06T17:43:33+07:00" level=info msg="Generate recipe for App: ./cmd/app/generated.go"
time="2019-08-06T17:43:33+07:00" level=info msg="Generate recipe for Typical-Dev-Tool: ./cmd/typical-dev-tool/generated.go"
time="2019-08-06T17:43:33+07:00" level=info msg="Typical Generated Code: typical/generated.go"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc7b300]

goroutine 1 [running]:
gopkg.in/src-d/go-git.v4/plumbing.(*Reference).Name(...)
	/var/lib/jenkins/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.12.0/plumbing/reference.go:178
github.com/typical-go/typical-rest-server/EXPERIMENTAL/typitask.ReleaseDistribution(0xec75e9, 0xc, 0xec08ca, 0x5, 0xed8882, 0x1e, 0x0, 0x0, 0x100e340, 0x180dfc0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/typical-go/typical-rest-server@v0.4.2/EXPERIMENTAL/typitask/release_distribution.go:55 +0x350
github.com/typical-go/typical-rest-server/EXPERIMENTAL/typimain.(*TypicalDevTool).execCommand.func1(0xc000101a20, 0x0, 0xc000101a20)
	/var/lib/jenkins/go/pkg/mod/github.com/typical-go/typical-rest-server@v0.4.2/EXPERIMENTAL/typimain/typical_dev_tool.go:157 +0xb9
gopkg.in/urfave/cli%2ev1.HandleAction(0xd34600, 0xc0001a48c0, 0xc000101a20, 0xc00041e700, 0x0)
	/var/lib/jenkins/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.Command.Run(0xec38b5, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed2c39, 0x18, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x996
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000bf6c0, 0xc000032180, 0x3, 0x3, 0x0, 0x0)
	/var/lib/jenkins/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x6af
main.main()
	/var/lib/jenkins/workspace/TIX-ORDER-GO/cmd/typical-dev-tool/main.go:13 +0xdf```

**Comment by imantung** [comment]
Fix at version 0.4.3
